### ISSUE TITLE
[BalanceTest] Add validation in dates that does not take date in past

### ISSUE THREAD

**Issue by TAU-MariaInesRobles** [TAU-FASTLab/DMP#9]
Add validation in dates that does not take date in past

![image](https://github.com/user-attachments/assets/05771294-bd81-4b05-8df8-633bf5d9c4c4)

**Comment by inesrob** [comment]
Code Test:
  // Prevent past dates in "date" field
  const dateField = document.getElementById('date');
  const dateDpoField = document.getElementById('dateDpo');
  
  // Set min attribute to today's date
  const today = new Date().toISOString().split('T')[0];
  dateField.setAttribute('min', today);
  dateDpoField.setAttribute('min', today);

  dateField.addEventListener('change', () => {
    if (new Date(dateField.value) < new Date(today)) {
      alert('Please select a date that is not in the past.');
      dateField.value = ''; // Reset the date field
    }
  });

  dateDpoField.addEventListener('change', () => {
    if (new Date(dateDpoField.value) < new Date(today)) {
      alert('Please select a date that is not in the past.');
      dateDpoField.value = ''; // Reset the date field
    }
  });
});

**Comment by inesrob** [comment]
Fixed! The past dates are not available for selection
![image](https://github.com/user-attachments/assets/9c2a3ecd-0e37-4930-8b44-9ad08764a1e8)
